name: Cleanup Old Images
on:
  schedule:
    - cron: '05 7 * * *'  # 7:05 UTC everyday
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@v1.0.13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: silverblue-custom,silverblue-nvidia-custom,kinoite-custom,kinoite-nvidia-custom,sericea-custom,sericea-nvidia-custom
          older-than: 90 days
          delete-orphaned-images: true
          #keep-n-tagged: 7
          #keep-n-untagged: 7
          #dry-run: true
